import React, { Component } from 'react';
import { Container, Card, CardItem, Body, Content } from 'native-base';
import {StyleSheet,Text, ScrollView, TouchableOpacity, Dimensions, Image, Linking,View} from 'react-native';
import { SocialIcon } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome5';
import {NavigationActions} from 'react-navigation';

export default class Tab4 extends Component {


    render(){
        return(
           <View>
           <View>
                <Image
                style={styles.banner}
                source={{uri:'https://careeratlic.in/img/success-4168389_1920.jpg'}}/>
                <ScrollView>
                    <View>
                    <View style={{justifyContent:'center', alignItems:'center'}}>
                   <Text style={{fontWeight:'700', fontSize:28,textDecorationLine:'underline',color:'#1D4E9E'}}>
                    Success Stories
                   </Text>
                   </View>
                        <Text style={{fontSize:18, margin:10}}>
                        Meet the Top Ranking Advisors from LIC Family Who Opted LIC Agency As Their Career Option Who Have Been Very Successful In The Insurance & Financial Sector
                        </Text>
                  
                   <Content padder>
                       <View style={{flexDirection:'row', justifyContent:'space-between'}}>
                       <View style={styles.cardv}>
                           <Image
                           style={styles.circleImage}
                           source={{uri:'https://careeratlic.in/img/Bharat-Parekh.jpg'}}/>
                      
                       <Text>
                       "He sells around 1,000 policies a year, the worth of a policy being Rs 2 lakh on an average, and manages to generate a premium of Rs 200 crore for the corporation — the highest generated by any agent in India."
                       </Text>
                       </View>

                       <View style={styles.cardv}>
                           <Image
                           style={styles.circleImage}
                           source={{uri:'https://careeratlic.in/img/ravi.jpg'}}/>
                      
                       <Text>
                       "It is glamorous to be a stock broker, but not an LIC agent. It was difficult to switch to insurance, but the stability made the sacrifice worthwhile. “I did not think it would become such a large piece of our business. The best part about the role is that it is like doing social service."
                       </Text>
                       </View>

                       <View style={styles.cardv}>
                           <Image
                           style={styles.circleImage}
                           source={{uri:'https://careeratlic.in/img/rajesh.jpg'}}/>
                      
                       <Text>
                      "I’ve been an Agent of The Life Insurance Corporation of India [LIC] for the last 29 years. Serving over 2000 valued customers, the majority of my clientele are High net-worth Individuals [HNI]. Out of the 14Lac agents all over India, I’ve consistently ranked in the Top 10 throughout his career in the business.

"
                       </Text>
                       </View>
                    </View>
                   </Content>
                   <Content >
         <View style={{backgroundColor:'#1D4E9E', margin:5, borderRadius:5}}>
           <Text style={{fontSize:24, margin:10, color:'white', fontWeight:'bold'}}>Jitendra Kumar Chaurasia</Text>
           <Text style={{fontSize:22, margin:10, color:'white',fontWeight:'600'}}>
             Development Officer / SBA{"\n"}LIC of India Delhi Div.II</Text>
             <TouchableOpacity style={{flexDirection:'row'}}
              onPress={()=>{Linking.openURL('tel:+(91) 888-254-8633');}}
             >
               <Icon name='phone' style={{margin:10,fontSize:22, color:'white'}}/>
             <Text style={{fontSize:18, margin:10, color:'white'}}>
         Mobile No : {"\n"}+(91) 888-254-8633/{"\n"}     9891237937
             </Text>
             </TouchableOpacity>

             <TouchableOpacity style={{flexDirection:'row'}}
             onPress={() => {
              Linking.openURL('mailto:lic.jitendrachaurasia@gmail.com');}}
             >
               <Icon name='envelope' style={{margin:10,fontSize:22, color:'white'}}/>
             <Text style={{fontSize:18, margin:10, color:'white'}}>
         E-Mail ID: {"\n"}lic.jitendrachaurasia@gmail.com
             </Text>
             </TouchableOpacity>

             <TouchableOpacity style={{flexDirection:'row'}}
             onPress={() => {
              Linking.openURL('https://careeratlic.in');}}
             >
               <Icon name='globe' style={{margin:10,fontSize:22, color:'white'}}/>
             <Text style={{fontSize:18, margin:10, color:'white'}}>
         Our Website: {"\n"}http://www.careeratlic.in
             </Text>
             </TouchableOpacity>

             <View style={{justifyContent:'center', alignItems:'center'}}>
                  
                   <Image
                   source={{uri:'https://content3.jdmagicbox.com/comp/tirupati/dc/9999px877.x877.1243409219d9a2q7.dc/catalogue/lic-of-india-tirupathi-ho-tirupati-life-insurance-agents-lic-y4u9xhc.jpg'}}
                   style={{height:100, width:((DEVICE_WIDTH)/2), resizeMode:'stretch'}}/>

                  <Text style={{fontWeight:'400', fontSize:15, margin:10, color:'white'}}>
                   Life Insurance Corporation of India is an Indian state-owned insurance group and investment company headquartered in Mumbai. It is the largest insurance company in India.
                   </Text>
            </View>
          
           <View >
             <View style={{flexDirection:'column', justifyContent:'center',alignItems:'center', marginBottom:10}}>
             <Text style={{fontSize:24, color:'white',}}>Follow Us On:</Text>
             <View style={{flexDirection:'row', justifyContent:'center', alignItems:'center'}}>
                <SocialIcon
                    onPress={() => {
                    Linking.openURL("https://api.whatsapp.com/send?phone= +91-99104 78707");}}
                    style={{backgroundColor:'green'}}
                    raised={true}
                    type='whatsapp'
                  />
                  
                  <SocialIcon
                    onPress={() => {
                      Linking.openURL('https://www.facebook.com/jitendra.chaurasia.338');}}
                    raised={true}
                    type='facebook'
                  />
                  
                  <SocialIcon
                  onPress={() => {
                    Linking.openURL('http://linkedin.com/in/jitendra-chaurasia-4b10a153');}}
                    raised={true}
                    type='linkedin'
                  />
                
                <TouchableOpacity
                 style={styles.ic}
                 onPress={() => {
                  Linking.openURL('mailto:lic.jitendrachaurasia@gmail.com');}}
                 >
                 <Icon name="envelope" style={{fontSize:20, color:'white'}}/>
                  </TouchableOpacity>
                  </View>
              </View>
           </View>

         </View>
       </Content>


                    </View>
                </ScrollView>
            </View>


           </View>
        );
    }
}

const DEVICE_WIDTH = Dimensions.get('window').width;
const DEVICE_HEIGHT = Dimensions.get('window').height;


const styles = StyleSheet.create({
    banner: {
        width: (DEVICE_WIDTH),
        height: 200,
        resizeMode:'stretch'
    },
    cardv: {
        flexDirection:'column',
        width:110,
        borderColor:'#000',
        borderRadius:5,
        borderWidth:0.5,
        justifyContent:'flex-start',
        alignItems:'center',
        padding:5,
    },
    circleImage: {
        width: 100,
        height:100,
        borderRadius: 100
    },
    ic :{
        padding:10, 
        height:50, 
        width:50,
        borderRadius:50,
        borderColor:'black',
        borderWidth:0.5,
        backgroundColor:'#B23121',
        justifyContent:'center',
        alignItems:'center',
      }
   
   });